export TOGETHER_AI_API_KEY="c6eca728ac361181b7f83bed335bf3c7f352ebea3c67f3132b347cc6c77c4c3e"
export NEXT_PUBLIC_BYTESCALE_API_KEY="public_12a1zACCXHE8j97gx6Q1rEQZR6Pa"

# The vector store you'd like to use.
# Can be one of "pinecone" or "mongodb"
# Defaults to "pinecone"
#export NEXT_PUBLIC_VECTORSTORE="pinecone"
export NEXT_PUBLIC_VECTORSTORE="mongodb"

export OPENAI_API_KEY="sk-TyPlEZwMpfCewSVXcByGYYrSn8JOg0qOkRn9PhBszIT3BlbkFJo1g1Ee5XFmYH9TOo6ERXmeeLLZHlHxk_yd0vSu57AA"

#export PINECONE_API_KEY="673868f2-dc5f-4c51-b507-6d55f24abd1a"
#export PINECONE_INDEX_NAME="rawi"
export MONGODB_ATLAS_URI="mongodb+srv://malek:EGkahL6Z7bDLPILA@rawi.2uvko.mongodb.net/?retryWrites=true&w=majority&appName=Rawi"
export MONGODB_ATLAS_DB_NAME="sample_mflix"
export MONGODB_ATLAS_COLLECTION_NAME="rawi"
export MONGODB_ATLAS_INDEX_NAME="vector_index"

export CLERK_SECRET_KEY="sk_test_SfUwNLkRZ6Idua0ZeCpka5sW3okqGBdaKB6BU1H9QN"
export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_Z3Jvd2luZy1zbmFwcGVyLTY5LmNsZXJrLmFjY291bnRzLmRldiQ"
export NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
export NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up

export POSTGRES_URL="postgresql://malek:malekrehan123@localhost:5432/malek2"
export POSTGRES_URL_NON_POOLING="postgresql://malek:malekrehan123@localhost:5432/malek2"
export POSTGRES_PRISMA_URL="postgresql://malek:malekrehan123@localhost:5432/malek2"

#export WATSONX_AI_AUTH_TYPE="iam"
#export WATSONX_AI_APIKEY="0newnC68i4NSE0zQiuOl5HhJNnaJvybXAlmwAFf1"

export WATSONX_AI_ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im5WZTRrVnZkc25JUUdrOWs0YzFRMlhrNjBmekhKSW1GUW5NWUJjN3A4ZkkifQ.eyJ1aWQiOiIxMDAwMzMxMDg1IiwidXNlcm5hbWUiOiJlN2E4MDZhNi1jODFkLTQzYWEtODZkMC01Y2YzOGNkZmUzMzEiLCJyb2xlIjoiVXNlciIsInBlcm1pc3Npb25zIjpbInNpZ25faW5fb25seSJdLCJncm91cHMiOlsxMDAzNywxMDAwMF0sInN1YiI6ImU3YTgwNmE2LWM4MWQtNDNhYS04NmQwLTVjZjM4Y2RmZTMzMSIsImlzcyI6IktOT1hTU08iLCJhdWQiOiJEU1giLCJhcGlfcmVxdWVzdCI6dHJ1ZSwiaWF0IjoxNzMwNzM2NDY0LCJleHAiOjUzMzA3MzI4NjR9.MPTJ0gZ5zZMtqJnArngdh-nHScS-3KBAAn5Yh2Mgj4k842uPCJW5KxPybgmn8IZTaDuKA5jJWWaNYqRNAodFxIgmgRWAKcRPSxurb-KDS-hPATnFKEAG4AsGzWRil3SLvO2KQNoV0fproN-DbHXAUKjkqjKVcZd3MV5_-q_lzlfPl_0rERdYzhJtZuARsgFyHMnumEEHrMdV1xpTZvtpHBKMXjBfYwisor1yGcC6gOJ5RAvbLeNZHFs86hcVBhZRv6h0yglSnwtJT1zu7TYH13NrN8wcVLr4AS80HuvxFFqsRLj1JTdAe-WDEvUOkA3II7jCoIYvFoj2Mg09k2vH0A"